/**
 * Google Gemini API Integration for Image Generation
 * Supports fast image generation with configurable models (including "nanobanana" if custom)
 */

// Configuration - can be set via environment variables
// Support both VITE_GEMINI_API_KEY and VITE_GEMINI_KEY for flexibility
const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY || import.meta.env.VITE_GEMINI_KEY || '';
const GEMINI_MODEL = import.meta.env.VITE_GEMINI_MODEL || 'gemini-3-pro-image-preview'; // Default to nanobanana model
const GEMINI_ENDPOINT = import.meta.env.VITE_GEMINI_ENDPOINT || 'https://generativelanguage.googleapis.com/v1beta';

// Timeout for image generation (60 seconds max)
const GENERATION_TIMEOUT = 60000;

interface GenerateImageParams {
  prompt: string;
  aspectRatio?: '1:1' | '16:9' | '9:16' | '4:3' | '3:4';
  numberOfImages?: number;
  safetySettings?: 'block_few' | 'block_some' | 'block_most' | 'block_none';
}

interface GenerateImageResponse {
  imageUrl: string;
  mimeType: string;
}

/**
 * Generates an image using Google Gemini/Imagen API
 */
export async function generateImageWithGemini({
  prompt,
  aspectRatio = '1:1',
  numberOfImages = 1,
  safetySettings = 'block_few',
}: GenerateImageParams): Promise<GenerateImageResponse> {
  if (!GEMINI_API_KEY) {
    throw new Error('Gemini API key is not configured. Please set VITE_GEMINI_API_KEY environment variable.');
  }

  // Check if using nanobanana model (custom or specific configuration)
  const modelName = GEMINI_MODEL.includes('nanobanana') ? GEMINI_MODEL : GEMINI_MODEL;
  
  // Construct the API endpoint
  const endpoint = `${GEMINI_ENDPOINT}/models/${modelName}:generateImages?key=${GEMINI_API_KEY}`;

  const requestBody = {
    prompt,
    number_of_images: numberOfImages,
    aspect_ratio: aspectRatio,
    safety_filter_level: safetySettings,
    person_generation: 'allow_all', // Allow generating people in images
  };

  try {
    // Create abort controller for timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), GENERATION_TIMEOUT);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        `Gemini API request failed: ${response.status} ${response.statusText}. ${
          errorData.error?.message || ''
        }`
      );
    }

    const data = await response.json();

    if (!data.generatedImages || data.generatedImages.length === 0) {
      throw new Error('No images were generated by the Gemini API');
    }

    // Get the first generated image
    const generatedImage = data.generatedImages[0];

    // Convert the base64 image to a data URL
    const imageUrl = `data:${generatedImage.mimeType};base64,${generatedImage.bytesBase64Encoded}`;

    return {
      imageUrl,
      mimeType: generatedImage.mimeType || 'image/png',
    };
  } catch (error) {
    if (error instanceof Error) {
      if (error.name === 'AbortError') {
        throw new Error('Image generation timed out. Please try again.');
      }
      throw error;
    }
    throw new Error('An unexpected error occurred during image generation');
  }
}

/**
 * Check if Gemini API is properly configured
 */
export function isGeminiConfigured(): boolean {
  return !!GEMINI_API_KEY && !!GEMINI_MODEL;
}

/**
 * Get the current Gemini model being used
 */
export function getGeminiModel(): string {
  return GEMINI_MODEL;
}
