/**
 * OpenAI API Integration for Image Generation and Text Generation
 * Uses DALL-E 3 for image generation and GPT-4 for text generation
 */

// Configuration - can be set via environment variables
const OPENAI_API_KEY = import.meta.env.VITE_OPENAI_API_KEY || '';
const OPENAI_ENDPOINT = 'https://api.openai.com/v1';

// Timeout for image generation (60 seconds max)
const GENERATION_TIMEOUT = 60000;

interface GenerateImageParams {
  prompt: string;
  size?: '1024x1024' | '1792x1024' | '1024x1792';
  quality?: 'standard' | 'hd';
  style?: 'vivid' | 'natural';
}

interface GenerateImageResponse {
  imageUrl: string;
  revisedPrompt?: string;
}

/**
 * Generates an image using OpenAI DALL-E 3 API
 */
export async function generateImageWithOpenAI({
  prompt,
  size = '1024x1024',
  quality = 'standard',
  style = 'vivid',
}: GenerateImageParams): Promise<GenerateImageResponse> {
  if (!OPENAI_API_KEY) {
    throw new Error('OpenAI API key is not configured. Please set VITE_OPENAI_API_KEY environment variable.');
  }

  const endpoint = `${OPENAI_ENDPOINT}/images/generations`;

  const requestBody = {
    model: 'dall-e-3',
    prompt,
    n: 1,
    size,
    quality,
    style,
    response_format: 'b64_json', // Get base64 encoded image
  };

  try {
    // Create abort controller for timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), GENERATION_TIMEOUT);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OPENAI_API_KEY}`,
      },
      body: JSON.stringify(requestBody),
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        `OpenAI API request failed: ${response.status} ${response.statusText}. ${
          errorData.error?.message || ''
        }`
      );
    }

    const data = await response.json();

    if (!data.data || data.data.length === 0) {
      throw new Error('No images were generated by the OpenAI API');
    }

    // Get the first generated image
    const generatedImage = data.data[0];

    // Convert the base64 image to a data URL
    const imageUrl = `data:image/png;base64,${generatedImage.b64_json}`;

    return {
      imageUrl,
      revisedPrompt: generatedImage.revised_prompt,
    };
  } catch (error) {
    if (error instanceof Error) {
      if (error.name === 'AbortError') {
        throw new Error('Image generation timed out. Please try again.');
      }
      throw error;
    }
    throw new Error('An unexpected error occurred during image generation');
  }
}

interface GenerateTextParams {
  prompt: string;
  systemPrompt?: string;
  model?: 'gpt-4' | 'gpt-4-turbo-preview' | 'gpt-3.5-turbo';
  maxTokens?: number;
  temperature?: number;
}

interface GenerateTextResponse {
  text: string;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

/**
 * Generates text using OpenAI GPT API
 */
export async function generateTextWithOpenAI({
  prompt,
  systemPrompt = 'You are a helpful assistant that helps people achieve their dreams and goals.',
  model = 'gpt-4-turbo-preview',
  maxTokens = 1000,
  temperature = 0.7,
}: GenerateTextParams): Promise<GenerateTextResponse> {
  if (!OPENAI_API_KEY) {
    throw new Error('OpenAI API key is not configured. Please set VITE_OPENAI_API_KEY environment variable.');
  }

  const endpoint = `${OPENAI_ENDPOINT}/chat/completions`;

  const requestBody = {
    model,
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: prompt },
    ],
    max_tokens: maxTokens,
    temperature,
  };

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), GENERATION_TIMEOUT);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OPENAI_API_KEY}`,
      },
      body: JSON.stringify(requestBody),
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        `OpenAI API request failed: ${response.status} ${response.statusText}. ${
          errorData.error?.message || ''
        }`
      );
    }

    const data = await response.json();

    if (!data.choices || data.choices.length === 0) {
      throw new Error('No text was generated by the OpenAI API');
    }

    return {
      text: data.choices[0].message.content,
      usage: data.usage ? {
        promptTokens: data.usage.prompt_tokens,
        completionTokens: data.usage.completion_tokens,
        totalTokens: data.usage.total_tokens,
      } : undefined,
    };
  } catch (error) {
    if (error instanceof Error) {
      if (error.name === 'AbortError') {
        throw new Error('Text generation timed out. Please try again.');
      }
      throw error;
    }
    throw new Error('An unexpected error occurred during text generation');
  }
}

/**
 * Check if OpenAI API is properly configured
 */
export function isOpenAIConfigured(): boolean {
  return !!OPENAI_API_KEY;
}

/**
 * Get available models
 */
export function getAvailableModels() {
  return {
    image: ['dall-e-3'],
    text: ['gpt-4', 'gpt-4-turbo-preview', 'gpt-3.5-turbo'],
  };
}

